-- Migration: Add home_abbr and away_abbr to q_matches
-- Populates existing rows with FIFA 3-letter abbreviations for flag lookup.
-- Safe: does NOT touch q_predictions or any other data.
-- Date: June 2026

ALTER TABLE q_matches
  ADD COLUMN home_abbr CHAR(3) DEFAULT NULL AFTER away_team,
  ADD COLUMN away_abbr CHAR(3) DEFAULT NULL AFTER home_abbr;

-- Populate abbreviations based on team names (group stage teams only)
-- Knockout placeholder names (e.g. "Group A Winner") remain NULL — no flags for those.
UPDATE q_matches SET
  home_abbr = CASE home_team
    WHEN 'Mexico'         THEN 'mex'
    WHEN 'South Africa'   THEN 'rsa'
    WHEN 'South Korea'    THEN 'kor'
    WHEN 'Czechia'        THEN 'cze'
    WHEN 'Canada'         THEN 'can'
    WHEN 'Bosnia-Herzegovina' THEN 'bih'
    WHEN 'Qatar'          THEN 'qat'
    WHEN 'Switzerland'    THEN 'sui'
    WHEN 'Brazil'         THEN 'bra'
    WHEN 'Morocco'        THEN 'mor'
    WHEN 'Haiti'          THEN 'hai'
    WHEN 'Scotland'       THEN 'sco'
    WHEN 'United States'  THEN 'usa'
    WHEN 'Paraguay'       THEN 'par'
    WHEN 'Australia'      THEN 'aus'
    WHEN 'Turkiye'        THEN 'tur'
    WHEN 'Germany'         THEN 'ger'
    WHEN 'Curacao'        THEN 'cuw'
    WHEN 'Ivory Coast'    THEN 'civ'
    WHEN 'Ecuador'        THEN 'ecu'
    WHEN 'Netherlands'    THEN 'ned'
    WHEN 'Japan'          THEN 'jpn'
    WHEN 'Sweden'         THEN 'swe'
    WHEN 'Tunisia'        THEN 'tun'
    WHEN 'Belgium'        THEN 'bel'
    WHEN 'Egypt'          THEN 'egy'
    WHEN 'Iran'           THEN 'irn'
    WHEN 'New Zealand'    THEN 'nzl'
    WHEN 'Spain'          THEN 'esp'
    WHEN 'Cape Verde'     THEN 'cpv'
    WHEN 'Saudi Arabia'   THEN 'ksa'
    WHEN 'Uruguay'        THEN 'uru'
    WHEN 'France'         THEN 'fra'
    WHEN 'Senegal'        THEN 'sen'
    WHEN 'Iraq'           THEN 'irq'
    WHEN 'Norway'         THEN 'nor'
    WHEN 'Argentina'      THEN 'arg'
    WHEN 'Algeria'        THEN 'alg'
    WHEN 'Austria'        THEN 'aut'
    WHEN 'Jordan'         THEN 'jor'
    WHEN 'Portugal'       THEN 'por'
    WHEN 'Congo DR'       THEN 'cod'
    WHEN 'Uzbekistan'     THEN 'uzb'
    WHEN 'Colombia'       THEN 'col'
    WHEN 'England'        THEN 'eng'
    WHEN 'Croatia'        THEN 'cro'
    WHEN 'Ghana'          THEN 'gha'
    WHEN 'Panama'         THEN 'pan'
    ELSE NULL
  END,
  away_abbr = CASE away_team
    WHEN 'Mexico'         THEN 'mex'
    WHEN 'South Africa'   THEN 'rsa'
    WHEN 'South Korea'    THEN 'kor'
    WHEN 'Czechia'        THEN 'cze'
    WHEN 'Canada'         THEN 'can'
    WHEN 'Bosnia-Herzegovina' THEN 'bih'
    WHEN 'Qatar'          THEN 'qat'
    WHEN 'Switzerland'    THEN 'sui'
    WHEN 'Brazil'         THEN 'bra'
    WHEN 'Morocco'        THEN 'mor'
    WHEN 'Haiti'          THEN 'hai'
    WHEN 'Scotland'       THEN 'sco'
    WHEN 'United States'  THEN 'usa'
    WHEN 'Paraguay'       THEN 'par'
    WHEN 'Australia'      THEN 'aus'
    WHEN 'Turkiye'        THEN 'tur'
    WHEN 'Germany'         THEN 'ger'
    WHEN 'Curacao'        THEN 'cuw'
    WHEN 'Ivory Coast'    THEN 'civ'
    WHEN 'Ecuador'        THEN 'ecu'
    WHEN 'Netherlands'    THEN 'ned'
    WHEN 'Japan'          THEN 'jpn'
    WHEN 'Sweden'         THEN 'swe'
    WHEN 'Tunisia'        THEN 'tun'
    WHEN 'Belgium'        THEN 'bel'
    WHEN 'Egypt'          THEN 'egy'
    WHEN 'Iran'           THEN 'irn'
    WHEN 'New Zealand'    THEN 'nzl'
    WHEN 'Spain'          THEN 'esp'
    WHEN 'Cape Verde'     THEN 'cpv'
    WHEN 'Saudi Arabia'   THEN 'ksa'
    WHEN 'Uruguay'        THEN 'uru'
    WHEN 'France'         THEN 'fra'
    WHEN 'Senegal'        THEN 'sen'
    WHEN 'Iraq'           THEN 'irq'
    WHEN 'Norway'         THEN 'nor'
    WHEN 'Argentina'      THEN 'arg'
    WHEN 'Algeria'        THEN 'alg'
    WHEN 'Austria'        THEN 'aut'
    WHEN 'Jordan'         THEN 'jor'
    WHEN 'Portugal'       THEN 'por'
    WHEN 'Congo DR'       THEN 'cod'
    WHEN 'Uzbekistan'     THEN 'uzb'
    WHEN 'Colombia'       THEN 'col'
    WHEN 'England'        THEN 'eng'
    WHEN 'Croatia'        THEN 'cro'
    WHEN 'Ghana'          THEN 'gha'
    WHEN 'Panama'         THEN 'pan'
    ELSE NULL
  END;
